import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import{createClient}from"genlayer-js";import{studionet}from"genlayer-js/chains";import{Hash,TransactionStatus}from"genlayer-js/types";import"./styles.css";
type RecordValue=Record<string,unknown>;type Entry={label:string;hash:string};
const POLICY=JSON.stringify({schema:"agent-spend-policy-v1",charter_ref:"OPS-AGENT-2026",purposes:[{purpose_id:"HOSTING",description:"Cloud hosting and infrastructure services."},{purpose_id:"API_CREDITS",description:"Developer API usage credits."}]},null,2);
const INVOICE=JSON.stringify({schema:"agent-invoice-v1",invoice_ref:"OPS-AGENT-2026",line_id:"LINE-01",narrative:"Managed cloud hosting service for October.",artifact_sha256:"11".repeat(32)},null,2);
const short=(v:string)=>v?`${v.slice(0,7)}…${v.slice(-5)}`:"—";
function App(){
 const[contract,setContractState]=useState(localStorage.getItem("asf-contract")||import.meta.env.VITE_CONTRACT_ADDRESS||"");const[account,setAccount]=useState("");const[message,setMessage]=useState("Set the deployed contract, connect a role wallet, then follow the numbered path.");const[busy,setBusy]=useState("");const[journal,setJournal]=useState<Entry[]>([]);const[record,setRecord]=useState<RecordValue|null>(null);
 const[agent,setAgent]=useState("");const[payee,setPayee]=useState("");const[asset,setAsset]=useState("0x0000000000000000000000000000000000000001");const[maxAmount,setMaxAmount]=useState("100");const[cap,setCap]=useState("300");const[policy,setPolicy]=useState(POLICY);
 const[charterId,setCharterId]=useState("0");const[amount,setAmount]=useState("40");const[packet,setPacket]=useState(INVOICE);const[invoiceId,setInvoiceId]=useState("0");const[nonce,setNonce]=useState("RUN-001");const[intentId,setIntentId]=useState("0");
 const reader=useMemo(()=>createClient({chain:studionet}),[]),valid=/^0x[0-9a-fA-F]{40}$/.test(contract);
 function setContract(v:string){setContractState(v);localStorage.setItem("asf-contract",v)}
 async function connect(){if(!window.ethereum)return setMessage("No injected wallet found.");try{const xs=await window.ethereum.request({method:"eth_requestAccounts"});if(!xs[0])throw new Error("No account selected");const c=createClient({chain:studionet,provider:window.ethereum,account:xs[0] as`0x${string}`});await c.connect("studionet");setAccount(xs[0]);setMessage("Wallet connected. It signs only the role assigned inside a charter.")}catch(e){setMessage(e instanceof Error?e.message:"Wallet connection cancelled")}}
 async function readValue(method:string,args:(string|number)[]=[]){if(!valid)throw new Error("Enter a valid deployed contract address.");return reader.readContract({address:contract as`0x${string}`,functionName:method,args})}
 function objectValue(value:unknown):RecordValue{const parsed=typeof value==="string"?JSON.parse(value):value;if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("Unexpected contract readback shape.");return parsed as RecordValue}
 async function readObject(method:string,args:(string|number)[]=[]){return objectValue(await readValue(method,args))}
 async function verifyContract(){const v=await readObject("get_contract_version");if(v.name!=="AgentSpendFirewall"||v.version!==1||v.schema!=="source-bound-agent-spend-v1")throw new Error("Contract identity mismatch. Write refused.")}
 async function load(kind:"charter"|"invoice"|"intent",id:string){if(!/^\d+$/.test(id))throw new Error("ID must be a non-negative integer.");const x=await readObject(`get_${kind}`,[Number(id)]);if(x.error)throw new Error(String(x.error));setRecord(x);return x}
 async function write(label:string,method:string,args:(string|number)[],kind:"charter"|"invoice"|"intent",target:string){if(!account||!window.ethereum)return setMessage("Connect the wallet assigned to this role first.");setBusy(method);try{await verifyContract();const counts=await readObject("get_counts");let before=-1;if(method==="create_charter"){before=Number(counts.charter_count);target=String(before)}if(method==="publish_invoice"){before=Number(counts.invoice_count);target=String(before)}if(method==="request_intent"){before=Number(counts.intent_count);target=String(before)}const writer=createClient({chain:studionet,provider:window.ethereum,account:account as`0x${string}`});await writer.connect("studionet");const hash=String(await writer.writeContract({address:contract as`0x${string}`,functionName:method,args,value:0n}));setJournal(v=>[{label,hash},...v]);setMessage("Signed. Waiting for finalized consensus and authoritative readback…");await reader.waitForTransactionReceipt({hash:hash as Hash,status:TransactionStatus.FINALIZED,interval:5000,retries:240});const after=await readObject("get_counts");if(before>=0){const key=method==="create_charter"?"charter_count":method==="publish_invoice"?"invoice_count":"intent_count";if(Number(after[key])!==before+1)throw new Error("Transaction finalized, but the contract rejected this operation; record count did not advance.");if(kind==="charter")setCharterId(target);if(kind==="invoice")setInvoiceId(target);if(kind==="intent")setIntentId(target)}const post=await load(kind,target);const expected:Record<string,string>={assess_intent:"AUTHORIZED|DENIED|REVIEW_REQUIRED",consume_authorization:"CONSUMED",revoke_charter:"REVOKED"};if(expected[method]&&!expected[method].split("|").includes(String(post.state)))throw new Error(`Transaction finalized, but chain state is ${post.state}; UI will not claim success.`);setMessage(`${label} finalized. Displayed state is a fresh chain readback.`)}catch(e){setMessage(e instanceof Error?e.message:`${label} failed`)}finally{setBusy("")}}
 const auth=record&&typeof record.authorization_sha256==="string"?record.authorization_sha256:"";
 return <><header><a className="brand" href="#top"><img src="/agent-spend-logo.png"/><span>AgentSpend<br/><b>Firewall</b></span></a><nav><a href="#how">How it works</a><a href="#charter">Create Charter</a><a href="#invoice">Publish Invoice</a><a href="#intent">Intent & Authorization</a><a href="#audit">Audit Evidence</a></nav><button className="connect" onClick={connect}>{account?short(account):"Connect wallet"}</button></header>
 <main id="top"><section className="hero"><div><p className="eyebrow">SOURCE-BOUND AUTONOMOUS WALLET CONTROL</p><h1>Let agents propose.<br/><em>Make policy decide.</em></h1><p className="lede">A GenLayer firewall that binds each spend intent to a principal-authored purpose policy and a payee-authenticated invoice before issuing a one-time authorization.</p><div className="badges"><span>Fail closed</span><span>Replay safe</span><span>Finalized readback</span></div></div><img className="hero-logo" src="/agent-spend-logo.png"/></section>
 <section id="how" className="how"><p className="eyebrow">HOW IT WORKS</p><h2>Four boundaries, one auditable decision</h2><div className="steps">{[["01","Principal seals scope","Defines agent, payee, asset, limits and allowed purposes."],["02","Payee binds evidence","Publishes a canonical invoice with a unique artifact hash."],["03","Network assesses","Consensus maps invoice purpose; ambiguity becomes REVIEW_REQUIRED."],["04","Agent consumes once","Digest, role, budget and revocation are rechecked before accounting."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
 <section className="console"><div className="console-head"><div><p className="eyebrow">STUDIONET CONSOLE</p><h2>Reproduce the lifecycle</h2></div><div className="contract"><label>DEPLOYED CONTRACT</label><input value={contract} onChange={e=>setContract(e.target.value)} placeholder="0x…"/></div></div><div className="status"><span className={busy?"pulse":"dot"}/>{message}</div>
 <div className="grid"><article id="charter" className="panel"><span className="num">01</span><p className="eyebrow">PRINCIPAL WALLET</p><h2>Create Charter</h2><label>Agent address<input value={agent} onChange={e=>setAgent(e.target.value)}/></label><label>Payee address<input value={payee} onChange={e=>setPayee(e.target.value)}/></label><label>Asset identifier<input value={asset} onChange={e=>setAsset(e.target.value)}/></label><div className="pair"><label>Per-intent max<input value={maxAmount} onChange={e=>setMaxAmount(e.target.value)}/></label><label>Lifetime cap<input value={cap} onChange={e=>setCap(e.target.value)}/></label></div><label>Canonical policy<textarea value={policy} onChange={e=>setPolicy(e.target.value)}/></label><button disabled={!!busy} onClick={()=>write("Charter creation","create_charter",[agent,asset,payee,Number(maxAmount),Number(cap),policy],"charter",charterId)}>Seal charter</button></article>
 <article id="invoice" className="panel"><span className="num">02</span><p className="eyebrow">DESIGNATED PAYEE WALLET</p><h2>Publish Invoice</h2><label>Charter ID<input value={charterId} onChange={e=>setCharterId(e.target.value)}/></label><label>Amount<input value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Canonical invoice packet<textarea value={packet} onChange={e=>setPacket(e.target.value)}/></label><button disabled={!!busy} onClick={()=>write("Invoice publication","publish_invoice",[Number(charterId),Number(amount),packet],"invoice",invoiceId)}>Bind invoice evidence</button></article>
 <article id="intent" className="panel wide"><span className="num">03</span><p className="eyebrow">DESIGNATED AGENT WALLET + OPEN ASSESSOR</p><h2>Intent & Authorization</h2><div className="triple"><label>Invoice ID<input value={invoiceId} onChange={e=>setInvoiceId(e.target.value)}/></label><label>Unique nonce<input value={nonce} onChange={e=>setNonce(e.target.value)}/></label><button disabled={!!busy} onClick={()=>write("Intent request","request_intent",[Number(invoiceId),nonce],"intent",intentId)}>Request intent</button></div><div className="triple"><label>Intent ID<input value={intentId} onChange={e=>setIntentId(e.target.value)}/></label><button className="secondary" disabled={!!busy} onClick={()=>write("Consensus assessment","assess_intent",[Number(intentId)],"intent",intentId)}>Assess purpose</button><button disabled={!!busy||!auth} onClick={()=>write("Authorization consumption","consume_authorization",[Number(intentId),auth],"intent",intentId)}>Consume once</button></div><div className="actions"><button className="ghost" onClick={()=>load("intent",intentId).catch(e=>setMessage(e.message))}>Reload intent</button><button className="ghost danger" disabled={!!busy} onClick={()=>write("Charter revocation","revoke_charter",[Number(charterId)],"charter",charterId)}>Revoke charter</button></div></article></div>
 <section id="audit" className="audit"><div><p className="eyebrow">AUTHORITATIVE READBACK</p><h2>Audit Evidence</h2><p>Every link below is a submitted transaction. The JSON is loaded from the finalized contract state, never inferred from a button click.</p></div><pre>{record?JSON.stringify(record,null,2):"Load or finalize a record to inspect its chain state."}</pre><div className="journal">{journal.length?journal.map(x=><a key={x.hash} target="_blank" rel="noreferrer" href={`https://explorer-studio.genlayer.com/tx/${x.hash}`}><span>{x.label}</span><code>{short(x.hash)}</code> ↗</a>):<p>No transactions signed in this browser session yet.</p>}</div></section></section>
 <footer><b>AgentSpend Firewall</b><span>Control plane only — no custody or token transfer.</span><a href="#how">Review design boundary ↑</a></footer></main></>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
